// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq9IykvQE_Jx0N1sVzYwTrDdeuDV_A32I',
    appId: '1:138121353976:web:4b1ae803577a3c658f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    authDomain: 'turassist-6fdc8.firebaseapp.com',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    measurementId: 'G-7XNR9BMFHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE9TEDgudXAWBnrNR_c3lrZdnNRrRZpRA',
    appId: '1:138121353976:android:bbb00948ed3c586e8f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQi45pOdLuVx7doWBGAf2LNTTk5jWnaWg',
    appId: '1:138121353976:ios:e67bf5b8b7f93c538f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    androidClientId: '138121353976-778rhpiqutpchele48e30nkp9tbru44l.apps.googleusercontent.com',
    iosClientId: '138121353976-n7vuio7cjumk8qgprlo0rcffbamkb6fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.turassistWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQi45pOdLuVx7doWBGAf2LNTTk5jWnaWg',
    appId: '1:138121353976:ios:e67bf5b8b7f93c538f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    androidClientId: '138121353976-778rhpiqutpchele48e30nkp9tbru44l.apps.googleusercontent.com',
    iosClientId: '138121353976-n7vuio7cjumk8qgprlo0rcffbamkb6fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.turassistWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq9IykvQE_Jx0N1sVzYwTrDdeuDV_A32I',
    appId: '1:138121353976:web:aefc166a8def6cf68f790d',
    messagingSenderId: '138121353976',
    projectId: 'turassist-6fdc8',
    authDomain: 'turassist-6fdc8.firebaseapp.com',
    storageBucket: 'turassist-6fdc8.firebasestorage.app',
    measurementId: 'G-8BQXC149EV',
  );
}
